### ISSUE TITLE
The template not working in window

### ISSUE THREAD

**Issue by dhrubrawat66** [geooot/zig-sokol-crossplatform-starter#4]
1.  I created the project by using the following template -->git clone https://github.com/geooot/zig-sokol-crossplatform-starter.git
2. then the run the following command ==> zig build run
3. this command throw following  error[](url)
![Screenshot 2024-05-26 102533](https://github.com/geooot/zig-sokol-crossplatform-starter/assets/85351405/1869608d-a4f6-45a4-935a-c88f2c94e02a)

**Comment by geooot** [comment]
Looks like you are not using the latest changes from zig-sokol-crossplatform-starter. Can you try again after pulling in the latest changes?

**Comment by dhrubrawat66** [comment]
thank you, now it working for zig build but not working for zig build android. which ndk version we need to install?

**Comment by geooot** [comment]
@dhrubrawat66 made some changes that should make the android build work on windows.

1. Pull the latest changes
2. Install the Android SDK. Specifcally use `sdkmanager` to install these components:
```
sdkmanager --install "platforms;android-32" "ndk;26.1.10909125" "build-tools"
```
3. Set the `ANDROID_HOME` environment variable to the folder where the android SDK is installed
4. `zig build android`
